# Generated by Django 2.1.7 on 2019-04-17 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название команды')),
                ('value', models.IntegerField(verbose_name='Значение')),
                ('description', models.CharField(max_length=255, verbose_name='Описание команды')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'db_table': 'Command',
            },
        ),
        migrations.CreateModel(
            name='CommandType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=20, verbose_name='Тип')),
                ('desMax', models.IntegerField(verbose_name='Максимальное значение')),
                ('desMin', models.IntegerField(verbose_name='Минимально значение')),
            ],
            options={
                'verbose_name': 'Тип команды',
                'verbose_name_plural': 'Типы команд',
                'db_table': 'CommandType',
            },
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'verbose_name': 'Устройства', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterModelOptions(
            name='macro',
            options={'verbose_name': 'Пользовательские макросы', 'verbose_name_plural': 'Пользовательские макросы'},
        ),
        migrations.AlterModelOptions(
            name='premissions',
            options={'verbose_name': 'Права', 'verbose_name_plural': 'Права'},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'Помещения', 'verbose_name_plural': 'Помещения'},
        ),
        migrations.AlterModelOptions(
            name='userpemissions',
            options={'verbose_name': 'Права пользователей', 'verbose_name_plural': 'Права пользователей'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='devices',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RemoteApp.Rooms', verbose_name='Помещение'),
        ),
        migrations.AddField(
            model_name='command',
            name='ctype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RemoteApp.CommandType', verbose_name='Тип команды'),
        ),
    ]
