# Generated by Django 2.1.7 on 2019-04-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteApp', '0002_auto_20190417_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RemoteApp.Devices', verbose_name='Устройство'),
            preserve_default=False,
        ),
    ]
