# Generated by Django 2.1.7 on 2019-04-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteApp', '0003_command_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='maxValue',
            field=models.IntegerField(null=True, verbose_name='Максимальное значение'),
        ),
        migrations.AddField(
            model_name='command',
            name='minValue',
            field=models.IntegerField(null=True, verbose_name='Минимальное значение'),
        ),
        migrations.AlterField(
            model_name='commandtype',
            name='desMax',
            field=models.IntegerField(verbose_name='Критическое максимальное значение'),
        ),
        migrations.AlterField(
            model_name='commandtype',
            name='desMin',
            field=models.IntegerField(verbose_name='Критическое минимальное значение'),
        ),
    ]
