# Generated by Django 2.1.7 on 2019-04-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteApp', '0004_auto_20190422_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.CharField(max_length=200, null=True, verbose_name='Уникальнай токен'),
        ),
    ]
