# Generated by Django 2.1.7 on 2019-06-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteApp', '0005_users_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='refreshToken',
            field=models.CharField(max_length=200, null=True, verbose_name='Токен обновления'),
        ),
    ]
