# Generated by Django 2.1.7 on 2019-06-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteApp', '0006_users_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='refreshToken',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Токен обновления'),
        ),
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Уникальнай токен'),
        ),
    ]
