# Generated by Django 2.1.7 on 2019-06-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteApp', '0007_auto_20190613_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
