# Generated by Django 2.1.7 on 2019-06-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteApp', '0008_users_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
