# Generated by Django 2.1.7 on 2019-06-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteApp', '0011_auto_20190620_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpemissions',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='userpemissions',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='permissions',
            field=models.ManyToManyField(to='RemoteApp.Premissions', verbose_name='Права'),
        ),
        migrations.DeleteModel(
            name='UserPemissions',
        ),
    ]
