# Generated by Django 2.1.7 on 2019-06-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteApp', '0012_auto_20190620_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
    ]
