# Generated by Django 2.1.7 on 2019-06-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteApp', '0013_users_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='permissions',
            field=models.ManyToManyField(null=True, to='RemoteApp.Premissions', verbose_name='Права'),
        ),
    ]
