# Generated by Django 2.1.7 on 2019-06-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteApp', '0014_auto_20190621_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='permissions',
            field=models.ManyToManyField(to='RemoteApp.Premissions', verbose_name='Права'),
        ),
    ]
