# Generated by Django 2.1.7 on 2019-06-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteApp', '0016_auto_20190621_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='driverIdenti',
            field=models.CharField(default='', max_length=50, verbose_name='имя команды внутри драйвера'),
        ),
    ]
